name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  go:
    name: Go
    uses: ./.github/workflows/go.yaml
    secrets: inherit

  changelog:
    runs-on: ubuntu-latest
    name: Changelog
    needs: [ "go" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --generate-notes --verify-tag "${GITHUB_REF#refs/*/}"
